version: 2

sources:
  - name: raw
    database: nicholas-erik-pipeline
    schema: agency_data_pipeline
    tables:
      - name: currencies_2
      - name: data_feeds
      - name: ebook_royalty_csv
      - name: combined_sales
      - name: KENP
      - name: KENP_read_csv
      - name: orders
      - name: paperback_royalty_csv
      - name: regions_2
      - name: portfolio
      - name: title_mappings_2
      - name: fb_ads_asin_mapping_2
      - name: region_to_currency_mapping
      - name: amzn_ebook_rates


  - name: raw_openbridge
    database: nicholas-erik-pipeline
    schema: nicholas_erik_openbridge
    tables:
      - name: amzadvertising_profiles_master
      - name: amzadvertising_sp_adgroups_master
      - name: amzadvertising_sp_campaigns_placement_master
      - name: amzadvertising_sp_campaigns_master
      - name: amzadvertising_sp_keywords_query_master
      - name: amzadvertising_sp_keywords_master
      - name: amzadvertising_sp_productads_master
      - name: amzadvertising_sp_targets_master
      - name: fbm_account_master
      - name: fbm_adset_master
      - name: fbm_ad_master
      - name: fbm_campaign_master

    