version: 2

sources:
  - name: raw
    database: nicholas-erik-pipeline
    schema: agency_data_pipeline
    tables:
      - name: amazon_orders
      - name: amzn_ebook_rates
      - name: combined_sales
      - name: currencies
      - name: data_feeds
      - name: ebook_royalties
      - name: fb_ads_asin_mapping
      - name: kenp
      - name: paperback_royalties
      - name: region_to_currency_mapping
      - name: regions
      - name: title_mappings

  - name: raw_openbridge
    database: nicholas-erik-pipeline
    schema: nicholas_erik_openbridge
    tables:
      - name: amzadvertising_profiles_master
      - name: amzadvertising_sp_adgroups_master
      - name: amzadvertising_sp_campaigns_placement_master
      - name: amzadvertising_sp_campaigns_master
      - name: amzadvertising_sp_keywords_query_master
      - name: amzadvertising_sp_keywords_master
      - name: amzadvertising_sp_productads_master
      - name: amzadvertising_sp_targets_master
      - name: fbm_account_master
      - name: fbm_adset_master
      - name: fbm_ad_master
      - name: fbm_campaign_master

    